/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SocioService } from "../socio.service";
import { SocioCreateInput } from "./SocioCreateInput";
import { Socio } from "./Socio";
import { SocioFindManyArgs } from "./SocioFindManyArgs";
import { SocioWhereUniqueInput } from "./SocioWhereUniqueInput";
import { SocioUpdateInput } from "./SocioUpdateInput";
import { InscripcionFindManyArgs } from "../../inscripcion/base/InscripcionFindManyArgs";
import { Inscripcion } from "../../inscripcion/base/Inscripcion";
import { InscripcionWhereUniqueInput } from "../../inscripcion/base/InscripcionWhereUniqueInput";
import { ServicioExtraFindManyArgs } from "../../servicioExtra/base/ServicioExtraFindManyArgs";
import { ServicioExtra } from "../../servicioExtra/base/ServicioExtra";
import { ServicioExtraWhereUniqueInput } from "../../servicioExtra/base/ServicioExtraWhereUniqueInput";

export class SocioControllerBase {
  constructor(protected readonly service: SocioService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Socio })
  async createSocio(@common.Body() data: SocioCreateInput): Promise<Socio> {
    return await this.service.createSocio({
      data: data,
      select: {
        activo: true,
        apellido: true,
        correo: true,
        createdAt: true,
        fechaRegistro: true,
        id: true,
        nombre: true,
        telefono: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Socio] })
  @ApiNestedQuery(SocioFindManyArgs)
  async socios(@common.Req() request: Request): Promise<Socio[]> {
    const args = plainToClass(SocioFindManyArgs, request.query);
    return this.service.socios({
      ...args,
      select: {
        activo: true,
        apellido: true,
        correo: true,
        createdAt: true,
        fechaRegistro: true,
        id: true,
        nombre: true,
        telefono: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Socio })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async socio(
    @common.Param() params: SocioWhereUniqueInput
  ): Promise<Socio | null> {
    const result = await this.service.socio({
      where: params,
      select: {
        activo: true,
        apellido: true,
        correo: true,
        createdAt: true,
        fechaRegistro: true,
        id: true,
        nombre: true,
        telefono: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Socio })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSocio(
    @common.Param() params: SocioWhereUniqueInput,
    @common.Body() data: SocioUpdateInput
  ): Promise<Socio | null> {
    try {
      return await this.service.updateSocio({
        where: params,
        data: data,
        select: {
          activo: true,
          apellido: true,
          correo: true,
          createdAt: true,
          fechaRegistro: true,
          id: true,
          nombre: true,
          telefono: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Socio })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSocio(
    @common.Param() params: SocioWhereUniqueInput
  ): Promise<Socio | null> {
    try {
      return await this.service.deleteSocio({
        where: params,
        select: {
          activo: true,
          apellido: true,
          correo: true,
          createdAt: true,
          fechaRegistro: true,
          id: true,
          nombre: true,
          telefono: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/inscripcions")
  @ApiNestedQuery(InscripcionFindManyArgs)
  async findInscripcions(
    @common.Req() request: Request,
    @common.Param() params: SocioWhereUniqueInput
  ): Promise<Inscripcion[]> {
    const query = plainToClass(InscripcionFindManyArgs, request.query);
    const results = await this.service.findInscripcions(params.id, {
      ...query,
      select: {
        createdAt: true,
        fechaFin: true,
        fechaInicio: true,
        id: true,
        plan: true,

        socio: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/inscripcions")
  async connectInscripcions(
    @common.Param() params: SocioWhereUniqueInput,
    @common.Body() body: InscripcionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inscripcions: {
        connect: body,
      },
    };
    await this.service.updateSocio({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/inscripcions")
  async updateInscripcions(
    @common.Param() params: SocioWhereUniqueInput,
    @common.Body() body: InscripcionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inscripcions: {
        set: body,
      },
    };
    await this.service.updateSocio({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/inscripcions")
  async disconnectInscripcions(
    @common.Param() params: SocioWhereUniqueInput,
    @common.Body() body: InscripcionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      inscripcions: {
        disconnect: body,
      },
    };
    await this.service.updateSocio({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/servicioExtras")
  @ApiNestedQuery(ServicioExtraFindManyArgs)
  async findServicioExtras(
    @common.Req() request: Request,
    @common.Param() params: SocioWhereUniqueInput
  ): Promise<ServicioExtra[]> {
    const query = plainToClass(ServicioExtraFindManyArgs, request.query);
    const results = await this.service.findServicioExtras(params.id, {
      ...query,
      select: {
        createdAt: true,
        fechaFin: true,
        fechaInicio: true,
        id: true,

        socio: {
          select: {
            id: true,
          },
        },

        tipoServicio: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/servicioExtras")
  async connectServicioExtras(
    @common.Param() params: SocioWhereUniqueInput,
    @common.Body() body: ServicioExtraWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      servicioExtras: {
        connect: body,
      },
    };
    await this.service.updateSocio({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/servicioExtras")
  async updateServicioExtras(
    @common.Param() params: SocioWhereUniqueInput,
    @common.Body() body: ServicioExtraWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      servicioExtras: {
        set: body,
      },
    };
    await this.service.updateSocio({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/servicioExtras")
  async disconnectServicioExtras(
    @common.Param() params: SocioWhereUniqueInput,
    @common.Body() body: ServicioExtraWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      servicioExtras: {
        disconnect: body,
      },
    };
    await this.service.updateSocio({
      where: params,
      data,
      select: { id: true },
    });
  }
}
