/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Socio } from "./Socio";
import { SocioCountArgs } from "./SocioCountArgs";
import { SocioFindManyArgs } from "./SocioFindManyArgs";
import { SocioFindUniqueArgs } from "./SocioFindUniqueArgs";
import { CreateSocioArgs } from "./CreateSocioArgs";
import { UpdateSocioArgs } from "./UpdateSocioArgs";
import { DeleteSocioArgs } from "./DeleteSocioArgs";
import { InscripcionFindManyArgs } from "../../inscripcion/base/InscripcionFindManyArgs";
import { Inscripcion } from "../../inscripcion/base/Inscripcion";
import { ServicioExtraFindManyArgs } from "../../servicioExtra/base/ServicioExtraFindManyArgs";
import { ServicioExtra } from "../../servicioExtra/base/ServicioExtra";
import { SocioService } from "../socio.service";
@graphql.Resolver(() => Socio)
export class SocioResolverBase {
  constructor(protected readonly service: SocioService) {}

  async _sociosMeta(
    @graphql.Args() args: SocioCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Socio])
  async socios(@graphql.Args() args: SocioFindManyArgs): Promise<Socio[]> {
    return this.service.socios(args);
  }

  @graphql.Query(() => Socio, { nullable: true })
  async socio(
    @graphql.Args() args: SocioFindUniqueArgs
  ): Promise<Socio | null> {
    const result = await this.service.socio(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Socio)
  async createSocio(@graphql.Args() args: CreateSocioArgs): Promise<Socio> {
    return await this.service.createSocio({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Socio)
  async updateSocio(
    @graphql.Args() args: UpdateSocioArgs
  ): Promise<Socio | null> {
    try {
      return await this.service.updateSocio({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Socio)
  async deleteSocio(
    @graphql.Args() args: DeleteSocioArgs
  ): Promise<Socio | null> {
    try {
      return await this.service.deleteSocio(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Inscripcion], { name: "inscripcions" })
  async findInscripcions(
    @graphql.Parent() parent: Socio,
    @graphql.Args() args: InscripcionFindManyArgs
  ): Promise<Inscripcion[]> {
    const results = await this.service.findInscripcions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [ServicioExtra], { name: "servicioExtras" })
  async findServicioExtras(
    @graphql.Parent() parent: Socio,
    @graphql.Args() args: ServicioExtraFindManyArgs
  ): Promise<ServicioExtra[]> {
    const results = await this.service.findServicioExtras(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
