/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsBoolean,
  IsOptional,
  IsString,
  MaxLength,
  IsDate,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { InscripcionUpdateManyWithoutSociosInput } from "./InscripcionUpdateManyWithoutSociosInput";
import { ServicioExtraUpdateManyWithoutSociosInput } from "./ServicioExtraUpdateManyWithoutSociosInput";

@InputType()
class SocioUpdateInput {
  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  activo?: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  apellido?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  correo?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  fechaRegistro?: Date | null;

  @ApiProperty({
    required: false,
    type: () => InscripcionUpdateManyWithoutSociosInput,
  })
  @ValidateNested()
  @Type(() => InscripcionUpdateManyWithoutSociosInput)
  @IsOptional()
  @Field(() => InscripcionUpdateManyWithoutSociosInput, {
    nullable: true,
  })
  inscripcions?: InscripcionUpdateManyWithoutSociosInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nombre?: string | null;

  @ApiProperty({
    required: false,
    type: () => ServicioExtraUpdateManyWithoutSociosInput,
  })
  @ValidateNested()
  @Type(() => ServicioExtraUpdateManyWithoutSociosInput)
  @IsOptional()
  @Field(() => ServicioExtraUpdateManyWithoutSociosInput, {
    nullable: true,
  })
  servicioExtras?: ServicioExtraUpdateManyWithoutSociosInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  telefono?: string | null;
}

export { SocioUpdateInput as SocioUpdateInput };
