/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Socio as PrismaSocio,
  Inscripcion as PrismaInscripcion,
  ServicioExtra as PrismaServicioExtra,
} from "@prisma/client";

export class SocioServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.SocioCountArgs, "select">): Promise<number> {
    return this.prisma.socio.count(args);
  }

  async socios(args: Prisma.SocioFindManyArgs): Promise<PrismaSocio[]> {
    return this.prisma.socio.findMany(args);
  }
  async socio(args: Prisma.SocioFindUniqueArgs): Promise<PrismaSocio | null> {
    return this.prisma.socio.findUnique(args);
  }
  async createSocio(args: Prisma.SocioCreateArgs): Promise<PrismaSocio> {
    return this.prisma.socio.create(args);
  }
  async updateSocio(args: Prisma.SocioUpdateArgs): Promise<PrismaSocio> {
    return this.prisma.socio.update(args);
  }
  async deleteSocio(args: Prisma.SocioDeleteArgs): Promise<PrismaSocio> {
    return this.prisma.socio.delete(args);
  }

  async findInscripcions(
    parentId: string,
    args: Prisma.InscripcionFindManyArgs
  ): Promise<PrismaInscripcion[]> {
    return this.prisma.socio
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .inscripcions(args);
  }

  async findServicioExtras(
    parentId: string,
    args: Prisma.ServicioExtraFindManyArgs
  ): Promise<PrismaServicioExtra[]> {
    return this.prisma.socio
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .servicioExtras(args);
  }
}
