/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ServicioExtra } from "./ServicioExtra";
import { ServicioExtraCountArgs } from "./ServicioExtraCountArgs";
import { ServicioExtraFindManyArgs } from "./ServicioExtraFindManyArgs";
import { ServicioExtraFindUniqueArgs } from "./ServicioExtraFindUniqueArgs";
import { CreateServicioExtraArgs } from "./CreateServicioExtraArgs";
import { UpdateServicioExtraArgs } from "./UpdateServicioExtraArgs";
import { DeleteServicioExtraArgs } from "./DeleteServicioExtraArgs";
import { Socio } from "../../socio/base/Socio";
import { ServicioExtraService } from "../servicioExtra.service";
@graphql.Resolver(() => ServicioExtra)
export class ServicioExtraResolverBase {
  constructor(protected readonly service: ServicioExtraService) {}

  async _servicioExtrasMeta(
    @graphql.Args() args: ServicioExtraCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ServicioExtra])
  async servicioExtras(
    @graphql.Args() args: ServicioExtraFindManyArgs
  ): Promise<ServicioExtra[]> {
    return this.service.servicioExtras(args);
  }

  @graphql.Query(() => ServicioExtra, { nullable: true })
  async servicioExtra(
    @graphql.Args() args: ServicioExtraFindUniqueArgs
  ): Promise<ServicioExtra | null> {
    const result = await this.service.servicioExtra(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ServicioExtra)
  async createServicioExtra(
    @graphql.Args() args: CreateServicioExtraArgs
  ): Promise<ServicioExtra> {
    return await this.service.createServicioExtra({
      ...args,
      data: {
        ...args.data,

        socio: args.data.socio
          ? {
              connect: args.data.socio,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => ServicioExtra)
  async updateServicioExtra(
    @graphql.Args() args: UpdateServicioExtraArgs
  ): Promise<ServicioExtra | null> {
    try {
      return await this.service.updateServicioExtra({
        ...args,
        data: {
          ...args.data,

          socio: args.data.socio
            ? {
                connect: args.data.socio,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ServicioExtra)
  async deleteServicioExtra(
    @graphql.Args() args: DeleteServicioExtraArgs
  ): Promise<ServicioExtra | null> {
    try {
      return await this.service.deleteServicioExtra(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Socio, {
    nullable: true,
    name: "socio",
  })
  async getSocio(
    @graphql.Parent() parent: ServicioExtra
  ): Promise<Socio | null> {
    const result = await this.service.getSocio(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
