/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ServicioExtraService } from "../servicioExtra.service";
import { ServicioExtraCreateInput } from "./ServicioExtraCreateInput";
import { ServicioExtra } from "./ServicioExtra";
import { ServicioExtraFindManyArgs } from "./ServicioExtraFindManyArgs";
import { ServicioExtraWhereUniqueInput } from "./ServicioExtraWhereUniqueInput";
import { ServicioExtraUpdateInput } from "./ServicioExtraUpdateInput";

export class ServicioExtraControllerBase {
  constructor(protected readonly service: ServicioExtraService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ServicioExtra })
  async createServicioExtra(
    @common.Body() data: ServicioExtraCreateInput
  ): Promise<ServicioExtra> {
    return await this.service.createServicioExtra({
      data: {
        ...data,

        socio: data.socio
          ? {
              connect: data.socio,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        fechaFin: true,
        fechaInicio: true,
        id: true,

        socio: {
          select: {
            id: true,
          },
        },

        tipoServicio: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ServicioExtra] })
  @ApiNestedQuery(ServicioExtraFindManyArgs)
  async servicioExtras(
    @common.Req() request: Request
  ): Promise<ServicioExtra[]> {
    const args = plainToClass(ServicioExtraFindManyArgs, request.query);
    return this.service.servicioExtras({
      ...args,
      select: {
        createdAt: true,
        fechaFin: true,
        fechaInicio: true,
        id: true,

        socio: {
          select: {
            id: true,
          },
        },

        tipoServicio: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ServicioExtra })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async servicioExtra(
    @common.Param() params: ServicioExtraWhereUniqueInput
  ): Promise<ServicioExtra | null> {
    const result = await this.service.servicioExtra({
      where: params,
      select: {
        createdAt: true,
        fechaFin: true,
        fechaInicio: true,
        id: true,

        socio: {
          select: {
            id: true,
          },
        },

        tipoServicio: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ServicioExtra })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateServicioExtra(
    @common.Param() params: ServicioExtraWhereUniqueInput,
    @common.Body() data: ServicioExtraUpdateInput
  ): Promise<ServicioExtra | null> {
    try {
      return await this.service.updateServicioExtra({
        where: params,
        data: {
          ...data,

          socio: data.socio
            ? {
                connect: data.socio,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          fechaFin: true,
          fechaInicio: true,
          id: true,

          socio: {
            select: {
              id: true,
            },
          },

          tipoServicio: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ServicioExtra })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteServicioExtra(
    @common.Param() params: ServicioExtraWhereUniqueInput
  ): Promise<ServicioExtra | null> {
    try {
      return await this.service.deleteServicioExtra({
        where: params,
        select: {
          createdAt: true,
          fechaFin: true,
          fechaInicio: true,
          id: true,

          socio: {
            select: {
              id: true,
            },
          },

          tipoServicio: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
