/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  ServicioExtra as PrismaServicioExtra,
  Socio as PrismaSocio,
} from "@prisma/client";

export class ServicioExtraServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ServicioExtraCountArgs, "select">
  ): Promise<number> {
    return this.prisma.servicioExtra.count(args);
  }

  async servicioExtras(
    args: Prisma.ServicioExtraFindManyArgs
  ): Promise<PrismaServicioExtra[]> {
    return this.prisma.servicioExtra.findMany(args);
  }
  async servicioExtra(
    args: Prisma.ServicioExtraFindUniqueArgs
  ): Promise<PrismaServicioExtra | null> {
    return this.prisma.servicioExtra.findUnique(args);
  }
  async createServicioExtra(
    args: Prisma.ServicioExtraCreateArgs
  ): Promise<PrismaServicioExtra> {
    return this.prisma.servicioExtra.create(args);
  }
  async updateServicioExtra(
    args: Prisma.ServicioExtraUpdateArgs
  ): Promise<PrismaServicioExtra> {
    return this.prisma.servicioExtra.update(args);
  }
  async deleteServicioExtra(
    args: Prisma.ServicioExtraDeleteArgs
  ): Promise<PrismaServicioExtra> {
    return this.prisma.servicioExtra.delete(args);
  }

  async getSocio(parentId: string): Promise<PrismaSocio | null> {
    return this.prisma.servicioExtra
      .findUnique({
        where: { id: parentId },
      })
      .socio();
  }
}
