/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Pago as PrismaPago,
  Inscripcion as PrismaInscripcion,
} from "@prisma/client";

export class PagoServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.PagoCountArgs, "select">): Promise<number> {
    return this.prisma.pago.count(args);
  }

  async pagos(args: Prisma.PagoFindManyArgs): Promise<PrismaPago[]> {
    return this.prisma.pago.findMany(args);
  }
  async pago(args: Prisma.PagoFindUniqueArgs): Promise<PrismaPago | null> {
    return this.prisma.pago.findUnique(args);
  }
  async createPago(args: Prisma.PagoCreateArgs): Promise<PrismaPago> {
    return this.prisma.pago.create(args);
  }
  async updatePago(args: Prisma.PagoUpdateArgs): Promise<PrismaPago> {
    return this.prisma.pago.update(args);
  }
  async deletePago(args: Prisma.PagoDeleteArgs): Promise<PrismaPago> {
    return this.prisma.pago.delete(args);
  }

  async getInscripcion(parentId: string): Promise<PrismaInscripcion | null> {
    return this.prisma.pago
      .findUnique({
        where: { id: parentId },
      })
      .inscripcion();
  }
}
