/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Pago } from "./Pago";
import { PagoCountArgs } from "./PagoCountArgs";
import { PagoFindManyArgs } from "./PagoFindManyArgs";
import { PagoFindUniqueArgs } from "./PagoFindUniqueArgs";
import { CreatePagoArgs } from "./CreatePagoArgs";
import { UpdatePagoArgs } from "./UpdatePagoArgs";
import { DeletePagoArgs } from "./DeletePagoArgs";
import { Inscripcion } from "../../inscripcion/base/Inscripcion";
import { PagoService } from "../pago.service";
@graphql.Resolver(() => Pago)
export class PagoResolverBase {
  constructor(protected readonly service: PagoService) {}

  async _pagosMeta(
    @graphql.Args() args: PagoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Pago])
  async pagos(@graphql.Args() args: PagoFindManyArgs): Promise<Pago[]> {
    return this.service.pagos(args);
  }

  @graphql.Query(() => Pago, { nullable: true })
  async pago(@graphql.Args() args: PagoFindUniqueArgs): Promise<Pago | null> {
    const result = await this.service.pago(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Pago)
  async createPago(@graphql.Args() args: CreatePagoArgs): Promise<Pago> {
    return await this.service.createPago({
      ...args,
      data: {
        ...args.data,

        inscripcion: args.data.inscripcion
          ? {
              connect: args.data.inscripcion,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Pago)
  async updatePago(@graphql.Args() args: UpdatePagoArgs): Promise<Pago | null> {
    try {
      return await this.service.updatePago({
        ...args,
        data: {
          ...args.data,

          inscripcion: args.data.inscripcion
            ? {
                connect: args.data.inscripcion,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Pago)
  async deletePago(@graphql.Args() args: DeletePagoArgs): Promise<Pago | null> {
    try {
      return await this.service.deletePago(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Inscripcion, {
    nullable: true,
    name: "inscripcion",
  })
  async getInscripcion(
    @graphql.Parent() parent: Pago
  ): Promise<Inscripcion | null> {
    const result = await this.service.getInscripcion(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
