/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PagoService } from "../pago.service";
import { PagoCreateInput } from "./PagoCreateInput";
import { Pago } from "./Pago";
import { PagoFindManyArgs } from "./PagoFindManyArgs";
import { PagoWhereUniqueInput } from "./PagoWhereUniqueInput";
import { PagoUpdateInput } from "./PagoUpdateInput";

export class PagoControllerBase {
  constructor(protected readonly service: PagoService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Pago })
  async createPago(@common.Body() data: PagoCreateInput): Promise<Pago> {
    return await this.service.createPago({
      data: {
        ...data,

        inscripcion: data.inscripcion
          ? {
              connect: data.inscripcion,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        fechaPago: true,
        id: true,

        inscripcion: {
          select: {
            id: true,
          },
        },

        metodoPago: true,
        monto: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Pago] })
  @ApiNestedQuery(PagoFindManyArgs)
  async pagos(@common.Req() request: Request): Promise<Pago[]> {
    const args = plainToClass(PagoFindManyArgs, request.query);
    return this.service.pagos({
      ...args,
      select: {
        createdAt: true,
        fechaPago: true,
        id: true,

        inscripcion: {
          select: {
            id: true,
          },
        },

        metodoPago: true,
        monto: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Pago })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async pago(
    @common.Param() params: PagoWhereUniqueInput
  ): Promise<Pago | null> {
    const result = await this.service.pago({
      where: params,
      select: {
        createdAt: true,
        fechaPago: true,
        id: true,

        inscripcion: {
          select: {
            id: true,
          },
        },

        metodoPago: true,
        monto: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Pago })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePago(
    @common.Param() params: PagoWhereUniqueInput,
    @common.Body() data: PagoUpdateInput
  ): Promise<Pago | null> {
    try {
      return await this.service.updatePago({
        where: params,
        data: {
          ...data,

          inscripcion: data.inscripcion
            ? {
                connect: data.inscripcion,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          fechaPago: true,
          id: true,

          inscripcion: {
            select: {
              id: true,
            },
          },

          metodoPago: true,
          monto: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Pago })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePago(
    @common.Param() params: PagoWhereUniqueInput
  ): Promise<Pago | null> {
    try {
      return await this.service.deletePago({
        where: params,
        select: {
          createdAt: true,
          fechaPago: true,
          id: true,

          inscripcion: {
            select: {
              id: true,
            },
          },

          metodoPago: true,
          monto: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
