/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Inscripcion as PrismaInscripcion,
  Pago as PrismaPago,
  Socio as PrismaSocio,
} from "@prisma/client";

export class InscripcionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.InscripcionCountArgs, "select">
  ): Promise<number> {
    return this.prisma.inscripcion.count(args);
  }

  async inscripcions(
    args: Prisma.InscripcionFindManyArgs
  ): Promise<PrismaInscripcion[]> {
    return this.prisma.inscripcion.findMany(args);
  }
  async inscripcion(
    args: Prisma.InscripcionFindUniqueArgs
  ): Promise<PrismaInscripcion | null> {
    return this.prisma.inscripcion.findUnique(args);
  }
  async createInscripcion(
    args: Prisma.InscripcionCreateArgs
  ): Promise<PrismaInscripcion> {
    return this.prisma.inscripcion.create(args);
  }
  async updateInscripcion(
    args: Prisma.InscripcionUpdateArgs
  ): Promise<PrismaInscripcion> {
    return this.prisma.inscripcion.update(args);
  }
  async deleteInscripcion(
    args: Prisma.InscripcionDeleteArgs
  ): Promise<PrismaInscripcion> {
    return this.prisma.inscripcion.delete(args);
  }

  async findPagos(
    parentId: string,
    args: Prisma.PagoFindManyArgs
  ): Promise<PrismaPago[]> {
    return this.prisma.inscripcion
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .pagos(args);
  }

  async getSocio(parentId: string): Promise<PrismaSocio | null> {
    return this.prisma.inscripcion
      .findUnique({
        where: { id: parentId },
      })
      .socio();
  }
}
