/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { InscripcionService } from "../inscripcion.service";
import { InscripcionCreateInput } from "./InscripcionCreateInput";
import { Inscripcion } from "./Inscripcion";
import { InscripcionFindManyArgs } from "./InscripcionFindManyArgs";
import { InscripcionWhereUniqueInput } from "./InscripcionWhereUniqueInput";
import { InscripcionUpdateInput } from "./InscripcionUpdateInput";
import { PagoFindManyArgs } from "../../pago/base/PagoFindManyArgs";
import { Pago } from "../../pago/base/Pago";
import { PagoWhereUniqueInput } from "../../pago/base/PagoWhereUniqueInput";

export class InscripcionControllerBase {
  constructor(protected readonly service: InscripcionService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Inscripcion })
  async createInscripcion(
    @common.Body() data: InscripcionCreateInput
  ): Promise<Inscripcion> {
    return await this.service.createInscripcion({
      data: {
        ...data,

        socio: data.socio
          ? {
              connect: data.socio,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        fechaFin: true,
        fechaInicio: true,
        id: true,
        plan: true,

        socio: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Inscripcion] })
  @ApiNestedQuery(InscripcionFindManyArgs)
  async inscripcions(@common.Req() request: Request): Promise<Inscripcion[]> {
    const args = plainToClass(InscripcionFindManyArgs, request.query);
    return this.service.inscripcions({
      ...args,
      select: {
        createdAt: true,
        fechaFin: true,
        fechaInicio: true,
        id: true,
        plan: true,

        socio: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Inscripcion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async inscripcion(
    @common.Param() params: InscripcionWhereUniqueInput
  ): Promise<Inscripcion | null> {
    const result = await this.service.inscripcion({
      where: params,
      select: {
        createdAt: true,
        fechaFin: true,
        fechaInicio: true,
        id: true,
        plan: true,

        socio: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Inscripcion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateInscripcion(
    @common.Param() params: InscripcionWhereUniqueInput,
    @common.Body() data: InscripcionUpdateInput
  ): Promise<Inscripcion | null> {
    try {
      return await this.service.updateInscripcion({
        where: params,
        data: {
          ...data,

          socio: data.socio
            ? {
                connect: data.socio,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          fechaFin: true,
          fechaInicio: true,
          id: true,
          plan: true,

          socio: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Inscripcion })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteInscripcion(
    @common.Param() params: InscripcionWhereUniqueInput
  ): Promise<Inscripcion | null> {
    try {
      return await this.service.deleteInscripcion({
        where: params,
        select: {
          createdAt: true,
          fechaFin: true,
          fechaInicio: true,
          id: true,
          plan: true,

          socio: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/pagos")
  @ApiNestedQuery(PagoFindManyArgs)
  async findPagos(
    @common.Req() request: Request,
    @common.Param() params: InscripcionWhereUniqueInput
  ): Promise<Pago[]> {
    const query = plainToClass(PagoFindManyArgs, request.query);
    const results = await this.service.findPagos(params.id, {
      ...query,
      select: {
        createdAt: true,
        fechaPago: true,
        id: true,

        inscripcion: {
          select: {
            id: true,
          },
        },

        metodoPago: true,
        monto: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/pagos")
  async connectPagos(
    @common.Param() params: InscripcionWhereUniqueInput,
    @common.Body() body: PagoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pagos: {
        connect: body,
      },
    };
    await this.service.updateInscripcion({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/pagos")
  async updatePagos(
    @common.Param() params: InscripcionWhereUniqueInput,
    @common.Body() body: PagoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pagos: {
        set: body,
      },
    };
    await this.service.updateInscripcion({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/pagos")
  async disconnectPagos(
    @common.Param() params: InscripcionWhereUniqueInput,
    @common.Body() body: PagoWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      pagos: {
        disconnect: body,
      },
    };
    await this.service.updateInscripcion({
      where: params,
      data,
      select: { id: true },
    });
  }
}
