/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Inscripcion } from "./Inscripcion";
import { InscripcionCountArgs } from "./InscripcionCountArgs";
import { InscripcionFindManyArgs } from "./InscripcionFindManyArgs";
import { InscripcionFindUniqueArgs } from "./InscripcionFindUniqueArgs";
import { CreateInscripcionArgs } from "./CreateInscripcionArgs";
import { UpdateInscripcionArgs } from "./UpdateInscripcionArgs";
import { DeleteInscripcionArgs } from "./DeleteInscripcionArgs";
import { PagoFindManyArgs } from "../../pago/base/PagoFindManyArgs";
import { Pago } from "../../pago/base/Pago";
import { Socio } from "../../socio/base/Socio";
import { InscripcionService } from "../inscripcion.service";
@graphql.Resolver(() => Inscripcion)
export class InscripcionResolverBase {
  constructor(protected readonly service: InscripcionService) {}

  async _inscripcionsMeta(
    @graphql.Args() args: InscripcionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Inscripcion])
  async inscripcions(
    @graphql.Args() args: InscripcionFindManyArgs
  ): Promise<Inscripcion[]> {
    return this.service.inscripcions(args);
  }

  @graphql.Query(() => Inscripcion, { nullable: true })
  async inscripcion(
    @graphql.Args() args: InscripcionFindUniqueArgs
  ): Promise<Inscripcion | null> {
    const result = await this.service.inscripcion(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Inscripcion)
  async createInscripcion(
    @graphql.Args() args: CreateInscripcionArgs
  ): Promise<Inscripcion> {
    return await this.service.createInscripcion({
      ...args,
      data: {
        ...args.data,

        socio: args.data.socio
          ? {
              connect: args.data.socio,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Inscripcion)
  async updateInscripcion(
    @graphql.Args() args: UpdateInscripcionArgs
  ): Promise<Inscripcion | null> {
    try {
      return await this.service.updateInscripcion({
        ...args,
        data: {
          ...args.data,

          socio: args.data.socio
            ? {
                connect: args.data.socio,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Inscripcion)
  async deleteInscripcion(
    @graphql.Args() args: DeleteInscripcionArgs
  ): Promise<Inscripcion | null> {
    try {
      return await this.service.deleteInscripcion(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Pago], { name: "pagos" })
  async findPagos(
    @graphql.Parent() parent: Inscripcion,
    @graphql.Args() args: PagoFindManyArgs
  ): Promise<Pago[]> {
    const results = await this.service.findPagos(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Socio, {
    nullable: true,
    name: "socio",
  })
  async getSocio(@graphql.Parent() parent: Inscripcion): Promise<Socio | null> {
    const result = await this.service.getSocio(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
